name: Multi Job Multi Step workflow

on:
  push:
    branches:
      - main

jobs:
  firstJob:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "This is the first step"
          echo "This is the second step"
          echo "This is the third step"
          echo "This is the fourth step"
  secondJob:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "This is the first step"
          echo "This is the second step"
          echo "This is the third step"
          echo "This is the fourth step"
  thirdJob:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "This is the first step"
          echo "This is the second step"
          echo "This is the third step"
          echo "This is the fourth step"
