name: Third Workflow

on:
  push:
    branches:
      - main

jobs:
  third_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is the first line of the third job"
      - run: echo "This is the second line of the third job"
      - run: echo "This is the third line of the third job"
